export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

// Brand
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRAND_FAIL = "GET_BRAND_FAIL";
export const INSERT_BRAND_SUCCESS = "INSERT_BRAND_SUCCESS";
export const INSERT_BRAND_FAIL = "INSERT_BRAND_FAIL";
export const UPDATE_BRAND_SUCCESS = "UPDATE_BRAND_SUCCESS";
export const UPDATE_BRAND_FAIL = "UPDATE_BRAND_FAIL";

// category
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS";
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL";
export const INSERT_CATEGORY_SUCCESS = "INSERT_CATEGORY_SUCCESS";
export const INSERT_CATEGORY_FAIL = "INSERT_CATEGORY_FAIL";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAIL = "UPDATE_CATEGORY_FAIL";

//Sale
export const GET_SALE_SUCCESS = "GET_SALE_SUCCESS";
export const GET_SALE_FAIL = "GET_SALE_FAIL";
export const UPDATE_SALE_SUCCESS = "UPDATE_SALE_SUCCESS";
export const UPDATE_SALE_FAIL = "UPDATE_SALE_FAIL";
export const INSERT_SALE_SUCCESS = "INSERT_SALE_SUCCESS";
export const INSERT_SALE_FAIL = "INSERT_SALE_FAIL";

//Product
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL";
export const INSERT_PRODUCT_SUCCESS = "INSERT_PRODUCT_SUCCESS";
export const INSERT_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
export const SELECTED_PRODUCT = "SELECTED_PRODUCT";
export const REMOVE_SELECTED_PRODUCT = "REMOVE_SELECTED_PRODUCT";

//cart
export const GET_NUMBER_CART = "GET_NUMBER_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const CLEAR_CART = "CLEAR_CART";

// Order
export const INSERT_ORDER_SUCCESS = "INSERT_ORDER_SUCCESS";
export const INSERT_ORDER_FAIL = "INSERT_ORDER_FAIL";
export const GET_ALL_ORDER_BY_USER_SUCCESS = "GET_ALL_ORDER_BY_USER_SUCCESS";
export const GET_ALL_ORDER_BY_USER_FAIL = "GET_ALL_ORDER_BY_USER_FAIL";
export const GET_ALL_ORDER_SUCCESS = "GET_ALL_ORDER_SUCCESS";
export const GET_ALL_ORDER_FAIL = "GET_ALL_ORDER_FAIL";
export const CANCEL_ORDER_SUCCESS = "CANCEL_ORDER_SUCCESS";
export const CANCEL_ORDER_FAIL = "CANCEL_ORDER_FAIL";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_FAIL = "UPDATE_ORDER_FAIL";

//User

export const GET_ALL_USER_SUCCESS = "GET_ALL_USER_SUCCESS";
export const GET_ALL_USER_FAIL = "GET_ALL_USER_FAIL";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL";
export const INSERT_USER_SUCCESS = "INSERT_USER_SUCCESS";
export const INSERT_USER_FAIL = "INSERT_USER_FAIL";
export const CHANGE_PASS_SUCCESS = "CHANGE_PASS_SUCCESS";
export const CHANGE_PASS_FAIL = "CHANGE_PASS_FAIL";

//Profile
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";

//SizeTable
export const GET_SIZETABLE_SUCCESS = "GET_SIZETABLE_SUCCESS";
export const GET_SIZETABLE_FAIL = "GET_SIZETABLE_FAIL";
export const UPDATE_SIZETABLE_SUCCESS = "UPDATE_SIZETABLE_SUCCESS";
export const UPDATE_SIZETABLE_FAIL = "UPDATE_SIZETABLE_FAIL";

//Status
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS";
export const GET_STATUS_FAIL = "GET_STATUS_FAIL";

//SaleDetails
export const GET_SALE_DETAILS_SUCCESS = "GET_SALE_DETAILS_SUCCESS";
export const GET_SALE_DETAILS_FAIL = "GET_SALE_DETAILS_FAIL";
export const DELETE_SALE_DETAILS_SUCCESS = "DELETE_SALE_DETAILS_SUCCESS";
export const DELETE_SALE_DETAILS_FAIL = "DELETE_SALE_DETAILS_FAIL";
export const GET_SALE_DETAILS_IS_COMING_SUCCESS = "GET_SALE_DETAILS_IS_COMING_SUCCESS";
export const GET_SALE_DETAILS_IS_COMING_FAIL = "GET_SALE_DETAILS_IS_COMING_FAIL";
export const GET_SALE_DETAILS_IS_ACTIVE_SUCCESS = "GET_SALE_DETAILS_IS_ACTIVE_SUCCESS";
export const GET_SALE_DETAILS_IS_ACTIVE_FAIL = "GET_SALE_DETAILS_IS_ACTIVE_FAIL";

export const INSERT_SALE_DETAILS_SUCCESS = "INSERT_SALE_DETAILS_SUCCESS";
export const INSERT_SALE_DETAILS_FAIL = "INSERT_SALE_DETAILS_FAIL";


